### ISSUE TITLE
manpage: acute-accent-in-manual-page

### ISSUE THREAD

**Issue by kartikm** [hills/xosview#17]
Debian's Lintian reported this:

```
I: xosview: acute-accent-in-manual-page usr/share/man/man1/xosview.1.gz:327
I: xosview: acute-accent-in-manual-page usr/share/man/man1/xosview.1.gz:328

```
More details: https://lintian.debian.org/tags/acute-accent-in-manual-page.html

**Comment by hills** [comment]
Accents were mistakenly being used as quotation marks. Followed the Debian doc to make a fix.
